### PR TITLE
Fix #4216 to make xml integration tests working in native build

### LINKED ISSUE #4216: [Camel 3.20] xml integration tests is failing on native build
https://github.com/apache/camel-quarkus/actions/runs/3325222823/jobs/5498333343

It could be related to camel-xslt-saxon.

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by JiriOndrusek — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

File: extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/XsltProcessor.java [hunk 1]
```diff
@@ -149,4 +150,10 @@ void xsltResources(
         }
     }
 
+    //It should be removed with fixing https://github.com/apache/camel-quarkus/issues/1615
+    @BuildStep
+    void runtimeInit(BuildProducer<RuntimeInitializedClassBuildItem> deps) {
+        deps.produce(new RuntimeInitializedClassBuildItem("org.apache.hc.client5.http.impl.auth.NTLMEngineImpl"));
```
Comment (essobedo) [inline extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/XsltProcessor.java:156]: Please note that since you have only one `RuntimeInitializedClassBuildItem` to produce, you could omit the producer and just return your instance of `RuntimeInitializedClassBuildItem`, something like:
```suggestion
    RuntimeInitializedClassBuildItem runtimeInit() {
        return new RuntimeInitializedClassBuildItem("org.apache.hc.client5.http.impl.auth.NTLMEngineImpl");
```

Comment (zhfeng) [reply extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/XsltProcessor.java:156]: @essobedo Thanks for the suggestion and it looks good to me.

**Review by essobedo — APPROVED** [review]
