### PR TITLE
Fix compareVersion in sanity-checks.groovy #5165

### LINKED ISSUE #5165: InvocationTargetException when running sanity-checks on 3.0.0-RC2
### Bug description

The steps to reproduce

1. Checkout on `3.0.0-RC2`
2. Run `./mvnw -f extension/ldap/pom.xml`
3. It will be failling with
```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:3.0.0:execute (sanity-checks) on project camel-quarkus-ldap: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: For input string: "0-RC2" -> [Help 1]
```

It needs to strip anything after "-" in `compareVersion` method in `tooling/scripts/sanity-checks.groovy`

### PR DESCRIPTION
**Pull request by zhfeng**
Fix #5165

### CODE REVIEW

**Review by aldettinger — APPROVED** [review]
Oh, String - regex in groovy. Looks good.

File: tooling/scripts/sanity-checks.groovy [hunk 1]
```diff
@@ -68,10 +68,11 @@ int compareVersion(String a, String b) {
     List verB = b.tokenize('.')
 
     def commonIndices = Math.min(verA.size(), verB.size())
+    def versionRegex = ~/\-.*/
 
     for (int i = 0; i < commonIndices; ++i) {
        def numA = verA[i].toInteger()
-       def numB = verB[i].toInteger()
+       def numB = (verB[i] - versionRegex).toInteger()
```
Comment (ppalaga) [inline tooling/scripts/sanity-checks.groovy:75]: I am bit lost what is this doing. The minus operator removes the matching part from the string, right?
I this way we are effectively disregard the `-RC` qualifiers, right? 
That's definitely OK for this current versions check, but I wonder whether it would not be safer for future copy-and-paste visitors, to move the suffix stripping before the compareVersion() method. After all we strip `-SNAPSHOT` from project.version before passing it to compareVersion() too.

Comment (ppalaga) [inline tooling/scripts/sanity-checks.groovy:75]: But wait, which version actually contains the -RC qualifier? Is it the current version or some of the since versions? Both of those sounds a bit strange.

Comment (zhfeng) [reply tooling/scripts/sanity-checks.groovy:75]: Only `currentVersion` contains `-RC`

Comment (zhfeng) [reply tooling/scripts/sanity-checks.groovy:75]: Yeah, it intends to strip `-RC`. So Maybe it could move before `compareVersion()` like
```java
final String currentVersion = project.version - '~/\-.*/'
```

Comment (ppalaga) [reply tooling/scripts/sanity-checks.groovy:75]: Yeah, I think that would be safer for any future reuse of `compareVersion()`

Comment (zhfeng) [reply tooling/scripts/sanity-checks.groovy]: OK, I fix it.

**Review by ppalaga — APPROVED** [review]

**Comment by ppalaga** [comment]
Thanks for taking care, @zhfeng
