### PR TITLE
Fix #428 XSLT extension does not work with file: URIs

### LINKED ISSUE #428: XSLT extension does not work with file: URIs
I just tried to extend the XsltTest with a `file:` use case and it fails. Let me try to fix it.

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

File: extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/BuildTimeUriResolver.java [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+import org.apache.camel.util.FileUtil;
+import org.apache.camel.util.StringHelper;
+
+public class BuildTimeUriResolver {
+
+    /** A directory to use as a base for resolving {@code file:} URIs */
+    private final Path baseDir;
+
+    public BuildTimeUriResolver(Path baseDir) {
+        super();
```
Comment (lburgazzoli) [inline extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/BuildTimeUriResolver.java]: not needed

File: extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java [hunk 2]
```diff
@@ -46,8 +56,7 @@ protected void configureEndpoint(
                 String remaining,
                 Map<String, Object> parameters) throws Exception {
 
-            final String fileName = FileUtil.stripExt(remaining, true);
-            final String className = StringHelper.capitalize(fileName, true);
+            final String className = uriResolver.getTransletClassName(remaining);
```
Comment (lburgazzoli) [inline extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java]: can you start working on the upstream component to support this feature natively ?

File: extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/BuildTimeUriResolver.java (hunk 1 above)
Comment (ppalaga) [reply extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/BuildTimeUriResolver.java]: Sorry, now found the setting in Eclipse to omit it next time.

File: extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java (hunk 2 above)
Comment (ppalaga) [reply extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java]: Not sure how that would make sense there because the upstream has no notion of build time/ runtime distinction? I mean a getTransletClassName() method could possibly be added to the upstream's XsltUriResolver, but the RuntimeUriResolver proposed here is quite different from it and am rather skeptical about letting RuntimeUriResolver to extend  XsltUriResolver. Or you mean something else?

**Comment by ppalaga** [comment]
9fb37b4 removes the redundant `super()` invocations

File: extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java (hunk 2 above)
Comment (lburgazzoli) [reply extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java]: I mean it would be nice to check what we need to to upstream to avoid having to subclass the component here.

**Comment by lburgazzoli** [comment]
ok to test

File: extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java (hunk 2 above)
Comment (ppalaga) [reply extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java]: OK, created https://github.com/apache/camel-quarkus/issues/441
