### PR TITLE
Revisit camel-quarkus bootstrap

### LINKED ISSUE #1037: Support Quarkus command mode
https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/command-mode-reference.adoc

camel-main supports giving some arguments from the command line. i.e. hoe many messages to wait before to shut down so it would be nice if we can optionally support Quarkus' command mode

### LINKED ISSUE #1128: Revisit camel-quarkus bootstrap
**Current State**

The **camel-quarkus-core** extension has two main responsibilities:
1. set-up the camel context
2. set-up the camel's main and start it

Camel's main support is an optional feature enabled by default that in essence:
- takes the camel context from 1
- configure the reactive engine
- collect routes
- collect main listeners
- start the main (which binds routes to the camel context and configure it using properties and other auto configuration steps)

With the introduction of the lightweight camel context in camel 3.2 and the work that is planned for for next versions the code may becoming more complex to maintain and the number of option may raise making the configuration harder for user.

**Proposal**

- **camle-quarkus-core**

  - configure context (reactive engine, registry, etc)
  - automatic discovery of routes and bind to the camel-context
  - provide a default "bootstrap item" that start the camel context

  <br />The main goal of this extension should be to provide the minimum needed to boot a camel based application which runs the routes available form the classpath / cdi container. This extension won't include a way to configure the context using `camel` properties name-space which is moved to the **camle-quarkus-main** extension. 

  User that need specific component/context configuration can use CDI (we probably need to support the concept of customizer with CDI beans).

- **camle-quarkus-main**

  - provides a alternative bootstrap to use camel-main to further configure the camel context configured by `camle-quarkus-core` and start it 

  <br />Among other things, this extension will include the support for the `camel` properties name-space making it more visible because as today, as example, it is not clear what you can do if you disable main through the `quarkus.camel.main` property but you still have the `camel` properties 

- **camle-quarkus-main-static** (name is just purely indicative)

  - provides a alternative bootstrap to use the static camel-main to start the camel context

  <br />The main goal here is to have a clear separation between default and static mode and have some more freedom to experiment. Eventually it could become the default bootstrap in the future but for the time being I think it could be better to have it in a dedicated extension so it is clear that it is for advanced and concious use.

### LINKED ISSUE #1368: CamelBeanPostProcessor is invoked after routes are already configured
In[ CamelMain::postProcessCamelContext](https://github.com/apache/camel-quarkus/blob/eb68674d83a7034445b895a358052be3a11719f5/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/CamelMain.java#L64-L74), the `CamelBeanPostProcessor` is invoked after routes are configured which causes the following route to fail as `myProcessor` is `null` when bound to the route.

```java
public class MyRoutes extends RouteBuilder {
    @BeanInject("my-processor")
    MyProcessor myProcessor;

    @Override
    public void configure() throws Exception {
        from("timer:tick")
            .process(myProcessor)
            .to("log:info");
    }
}
```

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #1128
Fixes #1037 
Fixes #1368 

TODO:
- [X] ~~overridable routes consumer~~ (not needed any-more)
- [x] cleanup
- [x] documentation (javadoc)
- [ ] documentation (user guide)
- [x] additional unit test
- [x] examples
- [x] support for command mode (requires Camel 3.4.0)

### CODE REVIEW

File: examples/timer-log-cdi/src/main/resources/application.properties [hunk 1]
```diff
@@ -14,33 +14,17 @@
...
-# the build process
-quarkus.camel.main.routes-discovery.enabled = false
-
-#
-# Camel
-#
-camel.context.name = quarkus-camel-example-timer-log-cdi
+# camel look-up beans using BeanManager so we don't want
+# ArC to remove beans without injection points.
+quarkus.arc.remove-unused-beans = false
```
Comment (davsclaus) [inline examples/timer-log-cdi/src/main/resources/application.properties:25]: Revisit this if this becomes a common use - I would like end users to not know or have to use such an option.

File: extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/CamelNativeImageProcessor.java [hunk 2]
```diff
@@ -0,0 +1,298 @@
...
+        DotName converter = DotName.createSimple(Converter.class.getName());
+        List<ClassInfo> converterClasses = view.getAnnotations(converter)
+                .stream()
+                .filter(ai -> ai.target().kind() == Kind.CLASS)
+                .filter(ai -> {
+                    AnnotationValue av = ai.value("loader");
+                    boolean isLoader = av != null && av.asBoolean();
+                    // filter out camel-base converters which are automatically inlined in the
+                    // CoreStaticTypeConverterLoader
+                    // need to revisit with Camel 3.0.0-M3 which should improve this area
```
Comment (davsclaus) [inline extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/CamelNativeImageProcessor.java:113]: Yeah all converters are now non-reflective, so we should look at this in another ticket

File: examples/timer-log-cdi/src/main/resources/application.properties (hunk 1 above)
Comment (lburgazzoli) [reply examples/timer-log-cdi/src/main/resources/application.properties:25]: It is possible to use the `@Unremovable` annotation as alternative but it's not better.

We probably need to discuss this topic with the Quarkus team and see if through a build item it could be possible to reverse the behaviour so not to remove beans unless that feature is turned on explicitly.

File: extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java [hunk 3]
```diff
@@ -66,7 +67,7 @@ public XMLRoutesDefinitionLoader getXmlRoutesLoader() {
         List<RoutesDefinition> answer = new ArrayList<>();
         PackageScanResourceResolver resolver = camelContext.adapt(ExtendedCamelContext.class).getPackageScanResourceResolver();
 
-        for (String part : directory.split(",")) {
+        for (String part : directory.split(",", -1)) {
```
Comment (ppalaga) [inline extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java:70]: Why do we need the empty trailing string here?

File: extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java [hunk 4]
```diff
@@ -90,7 +91,7 @@ public XMLRoutesDefinitionLoader getXmlRoutesLoader() {
         List<RestsDefinition> answer = new ArrayList<>();
         PackageScanResourceResolver resolver = camelContext.adapt(ExtendedCamelContext.class).getPackageScanResourceResolver();
 
-        for (String part : directory.split(",")) {
+        for (String part : directory.split(",", -1)) {
```
Comment (ppalaga) [inline extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java:94]: Why do we need the empty trailing string here?

File: docs/modules/ROOT/pages/extensions/main.adoc [hunk 5]
```diff
@@ -0,0 +1,22 @@
+// Do not edit directly!
+// This file was generated by camel-quarkus-package-maven-plugin:update-extension-doc-page
+
+[[main]]
+= Main
+
+[.badges]
+[.badge-key]##Since Camel Quarkus##[.badge-version]##1.0.0-CR3## [.badge-key]##JVM##[.badge-supported]##supported## [.badge-key]##Native##[.badge-supported]##supported##
+
+Camel Main
```
[the remark this answers is not in the document]
Comment (lburgazzoli) [reply docs/modules/ROOT/pages/extensions/main.adoc:10]: Yep this is still something in my TODO as part of the documentation tasks

File: extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/spi/CamelRuntimeBuildItem.java [hunk 6]
```diff
@@ -18,19 +18,16 @@
...
-    public CamelReactiveExecutorBuildItem(RuntimeValue<ReactiveExecutor> instance) {
-        this.instance = instance;
+    public CamelRuntimeBuildItem(RuntimeValue<CamelRuntime> runtime) {
+        this.runtime = runtime;
     }
 
-    public RuntimeValue<ReactiveExecutor> getInstance() {
-        return instance;
+    public RuntimeValue<CamelRuntime> get() {
+        return runtime;
```
[the remark this answers is not in the document]
Comment (lburgazzoli) [reply extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/spi/CamelRuntimeBuildItem.java:31]: I guess git got confused as I did remove the `ReactiveExecutorBuildItem` build item and I have introduced `CamelRuntimeBuildItem`

File: extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java (hunk 3 above)
Comment (lburgazzoli) [reply extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java:70]: thx to spot this, I don't really know what's the reason of such change

File: docs/modules/ROOT/pages/extensions/main.adoc (hunk 5 above)
[the remark this answers is not in the document]
Comment (lburgazzoli) [reply docs/modules/ROOT/pages/extensions/main.adoc:10]: done

File: extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/spi/CamelRuntimeTaskBuildItem.java [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.apache.camel.quarkus.core.deployment.spi;
+
+import io.quarkus.builder.item.MultiBuildItem;
+
+/**
+ * A symbolic class that represents a runtime task.
```
[the remark this answers is not in the document]
Comment (lburgazzoli) [reply extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/spi/CamelRuntimeTaskBuildItem.java]: done

File: extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java (hunk 3 above)
Comment (lburgazzoli) [reply extensions-core/main/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRoutesCollector.java]: done

File: extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/CamelNativeImageProcessor.java [hunk 8]
```diff
@@ -0,0 +1,298 @@
...
+
+        final IndexView view = combinedIndex.getIndex();
+
+        CAMEL_REFLECTIVE_CLASSES.stream()
+                .map(Class::getName)
+                .map(DotName::createSimple)
+                .map(view::getAllKnownImplementors)
+                .flatMap(Collection::stream)
+                .filter(CamelSupport::isPublic)
+                .forEach(v -> reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, v.name().toString())));
```
[the remark this answers is not in the document]
Comment (lburgazzoli) [reply extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/CamelNativeImageProcessor.java:102]: let postpone this

File: extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/spi/CamelRuntimeBuildItem.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (ppalaga) [reply extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/spi/CamelRuntimeBuildItem.java:31]: Sorry then

File: extensions-core/main/runtime/pom.xml [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+    <parent>
+        <groupId>org.apache.camel.quarkus</groupId>
+        <artifactId>camel-quarkus-main-parent</artifactId>
+        <version>1.1.0-SNAPSHOT</version>
+    </parent>
+    <modelVersion>4.0.0</modelVersion>
+
+    <artifactId>camel-quarkus-main</artifactId>
+    <name>Camel Quarkus :: Main :: Runtime</name>
+    <description>Bootstrap Camel using Camel Main which bring advanced auto-configuration capabilities and integration with Quarkus Command Mode</description>
```
Comment (ppalaga) [inline extensions-core/main/runtime/pom.xml:30]:
```suggestion
    <description>Bootstrap Camel using Camel Main which brings advanced auto-configuration capabilities and integration with Quarkus Command Mode</description>
```

**Comment by ppalaga** [comment]
What happens if the user app relies on configuration of components/languages/data-formats through properties AND camel-quarkus-main is not in class path? I think this will be a common source of app developer frustration. It would be nice if the error message could at least suggest to add camel-quarkus-main to CP.

**Comment by lburgazzoli** [comment]
> What happens if the user app relies on configuration of components/languages/data-formats through properties AND camel-quarkus-main is not in class path? I think this will be a common source of app developer frustration. It would be nice if the error message could at least suggest to add camel-quarkus-main to CP.

I'm not sure if I would log an error message i.e. assuming you have:

```
camel.component.slack.token = abc
```

Then the following code would be perfectly fine with or without camel-main:

```java
from("slack:room:?token={{camel.component.slack.token}}")
```

**Comment by ppalaga** [comment]
Could you plz name an example that would not work without camel-quarkus-main then?

**Comment by lburgazzoli** [comment]
> Could you plz name an example that would not work without camel-quarkus-main then?

Well, it is all about how the application is made so if you expect the value associated to the property `camel.component.slack.token` to be set to the `SlackComponent` then it won't work if you don't have `camel-main` but if you consume the same property using a place-holder or by injecting it, then it will work so a warning/error would be misleading too.

Anyway there are issues to move the advanced configuration from main to core, see:

- https://issues.apache.org/jira/browse/CAMEL-14600
- https://issues.apache.org/jira/browse/CAMEL-14672

File: docs/modules/ROOT/pages/user-guide/bootstrap.adoc [hunk 10]
```diff
@@ -0,0 +1,35 @@
+= Bootstrap Camel Quarkus
+:page-aliases: bootstrap.adoc
```
Comment (ppalaga) [inline docs/modules/ROOT/pages/user-guide/bootstrap.adoc:2]:
```suggestion
```
If bootstrap.adoc is  a new page, there is no point in adding an alias. Aliases serve for setting redirects and we use them mainly when we move a page.

File: docs/modules/ROOT/pages/user-guide/bootstrap.adoc [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+
+Camel Quarkus automatically configure and deploy a Camel Context bean which by default is started/stopped according to the Quarkus Application lifecycle. The configuration step happens at build time during Quarkus' augmentation phase and it is driven by the Camel Quarkus extensions which can be tuned using Camel Quarkus specific properties indentified by "camel.quarkus" as prefix. After the configuration is done, a minimal Camel Runtime is assembled and started at RUNTIME_INIT time. At that point, any additional configuration should be done using CDI, below an example bout how to configure a Camel Component:
```
Comment (ppalaga) [inline docs/modules/ROOT/pages/user-guide/bootstrap.adoc:4]:
```suggestion
Camel Quarkus automatically configures and deploys a Camel Context bean which by default is started/stopped according to the Quarkus Application lifecycle. The configuration step happens at build time during Quarkus' augmentation phase and it is driven by the Camel Quarkus extensions which can be tuned using Camel Quarkus specific `camel.quarkus.*` properties. After the configuration is done, a minimal Camel Runtime is assembled and started at `RUNTIME_INIT` time. At that point, any additional configuration should be done using CDI. Below is an example showing how to configure a Camel Component:
```

File: docs/modules/ROOT/pages/user-guide/bootstrap.adoc [hunk 12]
```diff
@@ -0,0 +1,35 @@
...
+
+[source,java]
+----
+@ApplicationScoped
```
Comment (ppalaga) [inline docs/modules/ROOT/pages/user-guide/bootstrap.adoc:8]: Please add all or at least the most important imports.

File: docs/modules/ROOT/pages/user-guide/bootstrap.adoc [hunk 13]
```diff
@@ -0,0 +1,35 @@
...
+
+        LogComponent component = new LogComponent();
+        component.setExchangeFormatter(formatter);
+
+        return component;
+    }
+}
+----
+
+To configure component and other aspects of Apache Camel through properties, you can add the camel-core-main extension which brings functionnalities from https://camel.apache.org/components/latest/others/main.html[Apache Camel Main] to Camel Quarkus. By adding such extension the programmatic configuration of the Log Component done above, can be done through properties:
```
Comment (ppalaga) [inline docs/modules/ROOT/pages/user-guide/bootstrap.adoc:27]:
```suggestion
To configure component and other aspects of Apache Camel through properties, you can add the `camel-core-main` extension which brings functionalities from https://camel.apache.org/components/latest/others/main.html[Apache Camel Main] to Camel Quarkus. By adding such extension the programmatic configuration of the Log Component done above, can be done through properties:
```

File: examples/timer-log-cdi/src/main/java/org/acme/timer/TimerRoute.java [hunk 14]
```diff
@@ -31,18 +31,24 @@
...
+     */
     @Inject
     Counter counter;
 
     @Override
     public void configure() throws Exception {
         fromF("timer:foo?period=%s", period)
                 .setBody(exchange -> "Incremented the counter: " + counter.increment())
-                .to("log:example?showExchangePattern=false&showBodyType=false");
+                // the configuration of the log component is programmatically done using CDI
```
Comment (ppalaga) [inline examples/timer-log-cdi/src/main/java/org/acme/timer/TimerRoute.java:50]:
```suggestion
                // the configuration of the log component is done programmatically using CDI
```

File: docs/modules/ROOT/pages/user-guide/bootstrap.adoc (hunk 11 above)
Comment (lburgazzoli) [reply docs/modules/ROOT/pages/user-guide/bootstrap.adoc:4]: I haven't yet marked the `documentation (user guide)` as done,
This is just a bunch of notes and I've committed it as I will continue on another computer so I need a way to synk them :)

**Comment by lburgazzoli** [comment]
Some tests for dev-mode have been disabled and require this fix: https://github.com/quarkusio/quarkus/pull/10109

**Comment by lburgazzoli** [comment]
@ppalaga @jamesnetherton @davsclaus @oscerd mind doing another review now that I've added support command mode ?

I'm still working on documentation and I had to disabled dev-mode tests because of a bug in quarkus but I'd like to merge this asap to avoid additional conflicts.

**Comment by davsclaus** [comment]
Great to see the command mode there.

File: examples/timer-log-cdi/src/main/resources/application.properties (hunk 1 above)
Comment (davsclaus) [reply examples/timer-log-cdi/src/main/resources/application.properties:25]: I think we should create a ticket about this, so its not forgotten. As end users this is a PITA to remember to have to do

**Comment by lburgazzoli** [comment]
> I noticed a minor typo, but that can be fixed up after merging if needed.

if it is only one, it is a great achievement for me :)

**Comment by jamesnetherton** [comment]
> if it is only one, it is a great achievement for me :)

And I forgot to submit the review comment but it's in `cusomt` in `examples/timer-log-main/README.adoc`.

File: examples/timer-log-cdi/src/main/resources/application.properties (hunk 1 above)
Comment (lburgazzoli) [reply examples/timer-log-cdi/src/main/resources/application.properties:25]: https://github.com/apache/camel-quarkus/issues/1387

**Comment by lburgazzoli** [comment]
> examples/timer-log-main/README.adoc

fixed
