### PR TITLE
Fix intermittent failures of SmallRyeReactiveMessagingIT

### LINKED ISSUE #1632: SmallRyeReactiveMessagingIT fails intermittently
This pops up on the CI build occasionally:

```
2020-08-26 14:45:15,849 INFO  [io.quarkus] (main) camel-quarkus-integration-test-smallrye-reactive-messaging 1.1.0-SNAPSHOT native (powered by Quarkus 1.7.1.Final) started in 0.026s. Listening on: http://0.0.0.0:33629
2020-08-26 14:45:15,849 INFO  [io.quarkus] (main) Profile prod activated. 
2020-08-26 14:45:15,849 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-direct, camel-file, camel-policy, camel-reactive-streams, camel-smallrye-reactive-messaging, camel-support-common, cdi, mutiny, resteasy, smallrye-context-propagation, smallrye-reactive-messaging, vertx]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.015 s <<< FAILURE! - in org.apache.camel.quarkus.component.smallrye.reactive.messaging.it.SmallRyeReactiveMessagingIT
[ERROR] testSmallRyeReactiveMessagingCamelRoutePublisher  Time elapsed: 10.869 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with org.apache.camel.quarkus.component.smallrye.reactive.messaging.it.SmallRyeReactiveMessagingTest was not fulfilled within 10 seconds.

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SmallRyeReactiveMessagingIT>SmallRyeReactiveMessagingTest.testSmallRyeReactiveMessagingCamelRoutePublisher:62 » ConditionTimeout
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0 
```

### PR DESCRIPTION
**Pull request by jamesnetherton**
Fixes #1632

### CODE REVIEW

**Review by lburgazzoli — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

File: integration-tests/smallrye-reactive-messaging/src/main/java/org/apache/camel/quarkus/component/smallrye/reactive/messaging/it/SmallRyeReactiveMessagingResource.java [hunk 1]
```diff
@@ -52,6 +54,8 @@ public Response post(String message) throws Exception {
     @Produces(MediaType.TEXT_PLAIN)
     @GET
     public String getValues() {
-        return String.join(",", results.getResults());
+        List<String> values = results.getResults();
+        Collections.sort(values);
```
Comment (ppalaga) [inline integration-tests/smallrye-reactive-messaging/src/main/java/org/apache/camel/quarkus/component/smallrye/reactive/messaging/it/SmallRyeReactiveMessagingResource.java:58]: Is this the actual fix?

**Review by ppalaga — APPROVED** [review]

File: integration-tests/smallrye-reactive-messaging/src/main/java/org/apache/camel/quarkus/component/smallrye/reactive/messaging/it/SmallRyeReactiveMessagingResource.java (hunk 1 above)
Comment (jamesnetherton) [reply integration-tests/smallrye-reactive-messaging/src/main/java/org/apache/camel/quarkus/component/smallrye/reactive/messaging/it/SmallRyeReactiveMessagingResource.java:58]: Yes. The order in which the messages are processed is not important. We just need to verify that all of the expected values are there.
