### PR TITLE
Fix intermittent failure of AHC-WS itest

### LINKED ISSUE #1815: Intermittent failure of AhcWsProducerConsumer
Pops up now and again on CI builds:

```
2020-09-22T03:22:10.4678375Z [ERROR] testAhcWsProducerConsumer  Time elapsed: 5.067 s  <<< FAILURE!
2020-09-22T03:22:10.4684715Z java.lang.AssertionError: 
2020-09-22T03:22:10.4689652Z 1 expectation failed.
2020-09-22T03:22:10.4698816Z Response body doesn't match expectation.
2020-09-22T03:22:10.4711279Z Expected: is "Hello Camel Quarkus AHC-WS"
2020-09-22T03:22:10.4716236Z   Actual: 
2020-09-22T03:22:10.4718262Z 
2020-09-22T03:22:10.4736164Z 	at org.apache.camel.quarkus.component.http.it.HttpTest.testAhcWsProducerConsumer(HttpTest.java:89)
2020-09-22T03:22:10.4740814Z 
2020-09-22T03:22:10.4774545Z 2020-09-22 03:22:10,476 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.5.0 (camel-1) is shutting down
2020-09-22T03:22:10.4856268Z 2020-09-22 03:22:10,484 INFO  [org.apa.cam.com.net.SingleTCPNettyServerBootstrapFactory] (main) ServerBootstrap unbinding from 0.0.0.0:44697
2020-09-22T03:22:10.4917803Z 2020-09-22 03:22:10,488 INFO  [org.apa.cam.com.net.NettyConsumer] (main) Netty consumer unbound from: 0.0.0.0:44697
2020-09-22T03:22:10.4934183Z 2020-09-22 03:22:10,492 INFO  [org.apa.cam.com.net.SingleTCPNettyServerBootstrapFactory] (main) ServerBootstrap unbinding from 0.0.0.0:34351
2020-09-22T03:22:10.5078221Z 2020-09-22 03:22:10,504 INFO  [org.apa.cam.com.net.NettyConsumer] (main) Netty consumer unbound from: 0.0.0.0:34351
2020-09-22T03:22:10.5537175Z 2020-09-22 03:22:10,553 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.5.0 (camel-1) uptime 9.538 seconds
2020-09-22T03:22:10.5541564Z 2020-09-22 03:22:10,553 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.5.0 (camel-1) is shutdown in 0.077 seconds
2020-09-22T03:22:10.5691479Z 2020-09-22 03:22:10,568 INFO  [io.quarkus] (main) Quarkus stopped in 0.108s
2020-09-22T03:22:10.6691602Z [INFO] 
2020-09-22T03:22:10.6693206Z [INFO] Results:
2020-09-22T03:22:10.6694033Z [INFO] 
2020-09-22T03:22:10.6695018Z [ERROR] Failures: 
2020-09-22T03:22:10.6696726Z [ERROR]   HttpTest.testAhcWsProducerConsumer:89 1 expectation failed.
2020-09-22T03:22:10.6699253Z Response body doesn't match expectation.
2020-09-22T03:22:10.6700781Z Expected: is "Hello Camel Quarkus AHC-WS"
2020-09-22T03:22:10.6703419Z   Actual: 
2020-09-22T03:22:10.6703738Z 
2020-09-22T03:22:10.6704121Z [INFO] 
```

### PR DESCRIPTION
**Pull request by jamesnetherton**
Fixes #1815

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: integration-tests/http/src/main/java/org/apache/camel/quarkus/component/http/it/GreetingServerEndpoint.java [hunk 1]
```diff
@@ -16,14 +16,34 @@
...
+import javax.websocket.OnOpen;
+import javax.websocket.Session;
 import javax.websocket.server.ServerEndpoint;
 
+import org.jboss.logging.Logger;
+
 @ServerEndpoint("/ahc-ws/greeting")
 public class GreetingServerEndpoint {
 
+    public static boolean connected = false;
```
Comment (ppalaga) [inline integration-tests/http/src/main/java/org/apache/camel/quarkus/component/http/it/GreetingServerEndpoint.java:30]: Shouldn't this be volatile? HttpResource.java is going to read it from a different thread and it would be better it if gets a non-cached value, wouldn't it?

Comment (jamesnetherton) [reply integration-tests/http/src/main/java/org/apache/camel/quarkus/component/http/it/GreetingServerEndpoint.java]: Yeah, you're right. Latest commit fixes that.

**Review by ppalaga — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Merging as test failure is not related to this change.
