### PR TITLE
xslt extension not working on java 11

### LINKED ISSUE #427: xslt extension not working on java 11
It appears that Java 11 introduces some changes to the underlying xslt engine that breaks how attributes are handled, in particular is is not possible to properly set the package name or the class name of the generated code as they get messed up

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #427

### CODE REVIEW

**Comment by lburgazzoli** [comment]
ok to test

File: extensions/support/xalan/runtime/src/main/java/org/apache/camel/quarkus/support/xalan/XalanSupport.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+public final class XalanSupport {
+    private static final Logger LOGGER = LoggerFactory.getLogger(XalanSupport.class);
+
+    private XalanSupport() {
+    }
+
+    public static TransformerFactory newTransformerFactoryInstance() {
+        TransformerFactory factory = TransformerFactory.newInstance(
+                "org.apache.xalan.xsltc.trax.TransformerFactoryImpl",
+                Thread.currentThread().getContextClassLoader());
```
Comment (ppalaga) [inline extensions/support/xalan/runtime/src/main/java/org/apache/camel/quarkus/support/xalan/XalanSupport.java]: This looks like the key part of the solution. If so, it would be nice to add a short comment explaining what problem is this snippet solving so that the future readers do not need to wonder.

Comment (lburgazzoli) [reply extensions/support/xalan/runtime/src/main/java/org/apache/camel/quarkus/support/xalan/XalanSupport.java]: Should I expand the description of the problem [here](https://github.com/apache/camel-quarkus/issues/427) ?

Comment (ppalaga) [reply extensions/support/xalan/runtime/src/main/java/org/apache/camel/quarkus/support/xalan/XalanSupport.java]: Question: we cannot pass `org.apache.xalan.xsltc.trax.TransformerFactoryImpl` as a standard service provider, right? We'd thus get the right implementation, but the class loader would still be wrong, right?

Comment (lburgazzoli) [reply extensions/support/xalan/runtime/src/main/java/org/apache/camel/quarkus/support/xalan/XalanSupport.java]: Probably we can use a standard service provider but that's the most "secure" way as you can't override it with a system property. If you know a better way please go ahead and send a PR

Comment (ppalaga) [reply extensions/support/xalan/runtime/src/main/java/org/apache/camel/quarkus/support/xalan/XalanSupport.java]: > Should I expand the description of the problem [here](https://github.com/apache/camel-quarkus/issues/427) ?

I meant a comment in the above newTransformerFactoryInstance() method. It might not be clear to the future readers why it is there. A single sentence would be enough, something like `This solves the translet class loading problems on Java 11+, see https://github.com/apache/camel-quarkus/issues/427`
